name: Algorithms CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      PYTHON_VERSION: '3.12'  # Set Python version as a global environment variable

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Dependencies
      run: make install

    - name: Run Unit Tests
      run: make test
